---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: istio-system
spec:
  values:
    global:
      azure:
        tenant: 58975fd3-4977-44d0-bea8-37af0baac100
        appid: ad53b0e9-539b-4916-b5b4-e172cbc8bbe8
